'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _10_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _9_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _9_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _9_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _9_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ace_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ace(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ace_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ace(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ace_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ace(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ace_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ace(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jack_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jack(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jack_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jack(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jack_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jack(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jack_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jack(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property King_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("King(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property King_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("King(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property King_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("King(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property King_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("King(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Queen_clubs_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen(clubs)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Queen_diamonds_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen(diamonds)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Queen_hearts_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen(hearts)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Queen_spades_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Queen(spades)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
